import type { Metadata } from "next";
import { Newsreader } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import LabelBottomNavigation from "../ui/navbars";

const newsreader = Newsreader({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={newsreader.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {children}
          <div className="fixed bottom-0 max-w-full text-gray-700 border-t-2">
            <LabelBottomNavigation />
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
